plugin: amazon.aws.aws_ec2
regions:
  - ap-northeast-1

filters:
  tag:Environment:
    - test

hostnames:
  - tag:Name

compose:
  ansible_host: instance_id

strict: False  # ← fail-safe（必須ではないが推奨）

keyed_groups:   # ← グループ分けしたい場合（省略も可能）
  - key: tags.Environment
    prefix: ""
    separator: ""
  - key: tags.Role
    prefix: ""
    separator: ""
