# GitHub Actionsワークフロー: Ansible SSM Test
# このワークフローは、GitHub ActionsからAWS SSM経由でEC2インスタンスに接続し、
# Ansibleを使用して操作を行うテストを実行します。

name: Ansible SSM Test

# ワークフローのトリガー設定
# mainブランチへのプッシュとプルリクエスト時に実行
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# GitHub Actionsの権限設定
# OIDC認証に必要な権限を付与
permissions:
  id-token: write  # OIDCトークン生成に必要
  contents: read   # リポジトリの読み取りに必要

jobs:
  test-ansible-ssm:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # AWS認証情報の設定
      # OIDCを使用してAWSの認証を行います
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::368017226728:role/GitHubActionsOidcRole
          aws-region: ap-northeast-1

      # Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Ansibleと必要なパッケージのインストール
      # - ansible: Ansible本体
      # - boto3: AWS SDK for Python
      # - amazon.aws: AWS用のAnsibleコレクション
      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install boto3
          ansible-galaxy collection install amazon.aws
          ansible-galaxy collection install community.aws
          ansible-galaxy collection install community.general

      # インベントリの確認
      - name: Verify inventory
        run: |
          ansible-inventory --list

      # Ansible Playbookの実行
      - name: Run Ansible playbook
        run: ansible-playbook playbooks/test-ssm.yml 